### ISSUE TITLE
Question consultation

### ISSUE THREAD

**Issue by yaolp123** [mrkolarik/3D-brain-segmentation#13]
Dear authors: 
    Recently I  have looking at your this project and feel interested in it ! After reading the github introduction, the URL is https://github.com/mrkolarik/3D-brain-segmentation, I face the question. That is, how can I find the dataset? In the project code, I could find the subfolds, such as train, test,mask, and I only find the txt file , like below of the train.txt:

This folder should contain only subfolders with train images which should be in the same order as in ../masks. Original code is written in a way that train images are contained in 21 subfolders each containing 256 images. Data.py lists all images in subfolders and creates train images matrix.

After reading, I could  assume there might be 21 subfolders for training, and 1 subfolder for testing? And what is the meaning of the 21 subfolders for masking, and why is the 21 subfolders?  Could I obtain the all the needed dataset needed in this project?

Thank you. I am looking forward to your reply Sincerely!

Best regards.

**Comment by mrkolarik** [comment]
Hi!

I am sorry to inform you the brain segmentation dataset is not published and probably will not be as the license for publishing with the local hospital is not clear. However in the paper there is used the spine segmentation dataset, which is accessible through the spineweb website.

Hope this helps and good luck with your research.

Martin
