### ISSUE TITLE
The spine dataset

### ISSUE THREAD

**Issue by CNUyue** [mrkolarik/3D-brain-segmentation#2]
Can you give me the spine dataset?
Thank you !

**Comment by mrkolarik** [comment]
Hi CNUyue,

dataset is available after signing agreement with terms of usage here:
http://spineweb.digitalimaginggroup.ca/spineweb/index.php?n=Main.Datasets
it is the dataset number 2 - I am unfortunately not permited to share the dataset. For loading and manipulating the data I recommend the Aliza:
https://www.aliza-dicom-viewer.com/
What an awesome piece of software!

Enjoy!
