### ISSUE TITLE
Preparing CT-Dataset

### ISSUE THREAD

**Issue by vaio05** [mrkolarik/3D-brain-segmentation#3]
Hey, I am trying to apply your network on a new dicom data set. It first has to be manually segmented, I guess different software programms can be used for this task. My question is in which data format should I store the ground truth labels, once they are labelled? 
Thanks for your help in advance!

**Comment by mrkolarik** [comment]
Hi,

work with Dicom is always hard, my implementation is done by loading folders containing .png 8bit greyscale images. But if you are able to load the dicom files into numpy arrays, it would be easier to apply them directly to the network without the data reformating.

Hope this helps, 

mrkolarik
