### ISSUE TITLE
The Brain Dataset

### ISSUE THREAD

**Issue by maryam-asadi** [mrkolarik/3D-brain-segmentation#4]
Where can I download the brain dataset you used in your work?
thanks

**Comment by mrkolarik** [comment]
Hi maryam,

its a database that has been collected during a research project on my university and has not yet been published. If you are a part of research team working on some publication I might be able to provide you with the data and work on some collaboration. If this is so, let me know :)

Martin

**Comment by maryam-asadi** [comment]
Hi Martin,

I will be so grateful if you share this dataset with us.

Thanks a million

**Comment by mrkolarik** [comment]
If this is still active issue, let me know to my email martin.kolarik@vutbr.cz and we can talk about some collaboration. I will close this in a week.

Take care
