### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by guohuigao** [mrkolarik/3D-brain-segmentation#7]
Hello, may I ask what kind of database you use, you can share your database, I have not found a suitable database. I’m sorry to bother you, but I need a dataset now. my email is 1939796898@qq.com

**Comment by mrkolarik** [comment]
Hi, all information regarding the dataset used in this work can be found in the paper - link is in the Readme. The Spine dataset is public and can be obtained, the MRI Brain one is private.
